{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# scikit-learn Pipeline Interoperability"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Because scikit-stan models all adhere to the scikit-learn API, they can be combined with methods from scikit-learn to form pipelines of operations. As such, scikit-stan can make use of the wide range of model operations provided by scikit-learn. Here, we show simple examples of incorporating scikit-stan models in pipelines with methods and other models from scikit-learn."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\tqdm\\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n"
     ]
    }
   ],
   "source": [
    "from scikit_stan import GLM\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "import matplotlib as mpl\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn import datasets \n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.model_selection import GridSearchCV"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "<style>\n",
       ".jp-RenderedImage, .output_png{\n",
       "    display: table-cell;\n",
       "    text-align: center;\n",
       "    vertical-align: middle;\n",
       "}\n",
       "</style>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "mpl.rc('axes.spines', top=True, bottom=True, left=True, right=True)\n",
    "#mpl.rc('axes', facecolor='white')\n",
    "mpl.rc(\"xtick\", bottom=True, labelbottom=True)\n",
    "mpl.rc(\"ytick\", left=True, labelleft=True)\n",
    "mpl.style.use('ggplot')\n",
    "\n",
    "\n",
    "# center images\n",
    "from IPython.core.display import HTML\n",
    "HTML(\"\"\"\n",
    "<style>\n",
    ".jp-RenderedImage, .output_png{\n",
    "    display: table-cell;\n",
    "    text-align: center;\n",
    "    vertical-align: middle;\n",
    "}\n",
    "</style>\n",
    "\"\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "X, y, true_weights = datasets.make_regression(\n",
    "    n_samples=100,\n",
    "    n_features=75,\n",
    "    n_informative=10,\n",
    "    noise=8,\n",
    "    coef=True,\n",
    "    random_state=42,\n",
    ")\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py:406: UserWarning: \n",
      "                    Link function not specified. Using default link function 'identity'\n",
      "                    for family 'gaussian'.\n",
      "                \n",
      "  \"\"\"\n",
      "c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py:500: UserWarning: Prior on intercept not specified. Using default prior.\n",
      "                alpha ~ normal(mu(y), 2.5 * sd(y)) if Gaussian family else normal(0, 2.5)\n",
      "  alpha ~ normal(mu(y), 2.5 * sd(y)) if Gaussian family else normal(0, 2.5)\"\"\"\n",
      "c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py:546: UserWarning: Prior on auxiliary parameter not specified. Using default unscaled prior\n",
      "                        sigma ~ exponential(1)\n",
      "                    \n",
      "  \"\"\"\n",
      "16:26:34 - cmdstanpy - INFO - CmdStan start processing\n",
      "chain 1 |\u001b[33m          \u001b[0m| 00:00 Status\n",
      "\u001b[A\n",
      "\n",
      "\u001b[A\u001b[A\n",
      "\n",
      "chain 1 |\u001b[33m▉         \u001b[0m| 00:00 Iteration:    1 / 2000 [  0%]  (Warmup)\n",
      "chain 1 |\u001b[33m████      \u001b[0m| 00:00 Iteration:  700 / 2000 [ 35%]  (Warmup)\n",
      "\u001b[A\n",
      "\n",
      "chain 1 |\u001b[34m█████▉    \u001b[0m| 00:00 Iteration: 1001 / 2000 [ 50%]  (Sampling)\n",
      "\n",
      "\u001b[A\u001b[A\n",
      "\u001b[A\n",
      "\n",
      "chain 1 |\u001b[34m███████▋  \u001b[0m| 00:00 Iteration: 1400 / 2000 [ 70%]  (Sampling)\n",
      "\u001b[A\n",
      "\n",
      "chain 1 |\u001b[34m█████████ \u001b[0m| 00:01 Iteration: 1700 / 2000 [ 85%]  (Sampling)\n",
      "\u001b[A\n",
      "\n",
      "chain 1 |\u001b[34m██████████\u001b[0m| 00:01 Sampling completed                       \n",
      "chain 2 |\u001b[34m██████████\u001b[0m| 00:01 Sampling completed                       \n",
      "chain 3 |\u001b[34m██████████\u001b[0m| 00:01 Sampling completed                       \n",
      "chain 4 |\u001b[34m██████████\u001b[0m| 00:01 Sampling completed                       "
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                                                                                                                                                                                                                                                                                                                                "
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "16:26:35 - cmdstanpy - INFO - CmdStan done processing.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "16:26:36 - cmdstanpy - INFO - Chain [1] start processing\n",
      "16:26:36 - cmdstanpy - INFO - Chain [2] start processing\n",
      "16:26:36 - cmdstanpy - INFO - Chain [3] start processing\n",
      "16:26:36 - cmdstanpy - INFO - Chain [4] start processing\n",
      "16:26:37 - cmdstanpy - INFO - Chain [1] done processing\n",
      "16:26:37 - cmdstanpy - INFO - Chain [3] done processing\n",
      "16:26:37 - cmdstanpy - INFO - Chain [2] done processing\n",
      "16:26:37 - cmdstanpy - INFO - Chain [4] done processing\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "0.9911734663273118"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pipe = Pipeline([('scaler', StandardScaler()), ('glm', GLM( seed=1234))])\n",
    "pipe.fit(X_train, y_train)\n",
    "pipe.score(X_test, y_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py:406: UserWarning: \n",
      "                    Link function not specified. Using default link function 'identity'\n",
      "                    for family 'gaussian'.\n",
      "                \n",
      "  \"\"\"\n",
      "c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py:500: UserWarning: Prior on intercept not specified. Using default prior.\n",
      "                alpha ~ normal(mu(y), 2.5 * sd(y)) if Gaussian family else normal(0, 2.5)\n",
      "  alpha ~ normal(mu(y), 2.5 * sd(y)) if Gaussian family else normal(0, 2.5)\"\"\"\n",
      "c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py:546: UserWarning: Prior on auxiliary parameter not specified. Using default unscaled prior\n",
      "                        sigma ~ exponential(1)\n",
      "                    \n",
      "  \"\"\"\n",
      "16:26:41 - cmdstanpy - INFO - CmdStan start processing\n",
      "chain 1 |\u001b[33m          \u001b[0m| 00:00 Status\n",
      "\u001b[A\n",
      "\n",
      "\u001b[A\u001b[A\n",
      "\n",
      "chain 1 |\u001b[33m▉         \u001b[0m| 00:00 Iteration:    1 / 2000 [  0%]  (Warmup)\n",
      "\u001b[A\n",
      "\n",
      "chain 1 |\u001b[33m███▋      \u001b[0m| 00:00 Iteration:  600 / 2000 [ 30%]  (Warmup)\n",
      "\u001b[A\n",
      "\n",
      "chain 1 |\u001b[34m█████▉    \u001b[0m| 00:00 Iteration: 1001 / 2000 [ 50%]  (Sampling)\n",
      "\u001b[A\n",
      "\n",
      "chain 1 |\u001b[34m███████▋  \u001b[0m| 00:00 Iteration: 1400 / 2000 [ 70%]  (Sampling)\n",
      "\n",
      "\u001b[A\u001b[A\n",
      "chain 1 |\u001b[34m█████████ \u001b[0m| 00:01 Iteration: 1700 / 2000 [ 85%]  (Sampling)\n",
      "\u001b[A\n",
      "\n",
      "\u001b[A\u001b[A\n",
      "\n",
      "chain 1 |\u001b[34m██████████\u001b[0m| 00:01 Sampling completed                       \n",
      "chain 2 |\u001b[34m██████████\u001b[0m| 00:01 Sampling completed                       \n",
      "chain 3 |\u001b[34m██████████\u001b[0m| 00:01 Sampling completed                       \n",
      "chain 4 |\u001b[34m██████████\u001b[0m| 00:01 Sampling completed                       "
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                                                                                                                                                                                                                                                                                                                                "
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "16:26:43 - cmdstanpy - INFO - CmdStan done processing.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "16:26:44 - cmdstanpy - INFO - Chain [1] start processing\n",
      "16:26:44 - cmdstanpy - INFO - Chain [2] start processing\n",
      "16:26:44 - cmdstanpy - INFO - Chain [3] start processing\n",
      "16:26:44 - cmdstanpy - INFO - Chain [4] start processing\n",
      "16:26:45 - cmdstanpy - INFO - Chain [3] done processing\n",
      "16:26:45 - cmdstanpy - INFO - Chain [1] done processing\n",
      "16:26:45 - cmdstanpy - INFO - Chain [2] done processing\n",
      "16:26:45 - cmdstanpy - INFO - Chain [4] done processing\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "0.9899535381342051"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "glm_unscaled = GLM(seed=1234) \n",
    "glm_unscaled.fit(X_train, y_train)\n",
    "glm_unscaled.score(X_test, y_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn import preprocessing\n",
    "pca = PCA()\n",
    "scaler = StandardScaler()\n",
    "mmscaler = preprocessing.MinMaxScaler(feature_range=(0, 1))\n",
    "logisticregression = GLM(algorithm=\"optimize\", family=\"bernoulli\", link=\"logit\", seed=1234, )\n",
    "\n",
    "pipeline = Pipeline(steps=[('scaler', scaler), ('pca', pca), ('mmscaler', mmscaler), ('logistic', logisticregression)])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "Expected 2D array, got 1D array instead:\narray=[0. 1. 2. ... 8. 9. 8.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_19448\\1873511765.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[0mx_digits\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my_digits\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mdatasets\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mload_digits\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mreturn_X_y\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[0mscaler\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit_transform\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mx_digits\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 3\u001b[1;33m \u001b[0mscaler\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit_transform\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0my_digits\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32mc:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\base.py\u001b[0m in \u001b[0;36mfit_transform\u001b[1;34m(self, X, y, **fit_params)\u001b[0m\n\u001b[0;32m    850\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0my\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    851\u001b[0m             \u001b[1;31m# fit method of arity 1 (unsupervised transformation)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 852\u001b[1;33m             \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mfit_params\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtransform\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    853\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    854\u001b[0m             \u001b[1;31m# fit method of arity 2 (supervised transformation)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\preprocessing\\_data.py\u001b[0m in \u001b[0;36mfit\u001b[1;34m(self, X, y, sample_weight)\u001b[0m\n\u001b[0;32m    804\u001b[0m         \u001b[1;31m# Reset internal state before fitting\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    805\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_reset\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 806\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpartial_fit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0msample_weight\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    807\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    808\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mpartial_fit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mNone\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0msample_weight\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mNone\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\preprocessing\\_data.py\u001b[0m in \u001b[0;36mpartial_fit\u001b[1;34m(self, X, y, sample_weight)\u001b[0m\n\u001b[0;32m    845\u001b[0m             \u001b[0mdtype\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mFLOAT_DTYPES\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    846\u001b[0m             \u001b[0mforce_all_finite\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m\"allow-nan\"\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 847\u001b[1;33m             \u001b[0mreset\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mfirst_call\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    848\u001b[0m         )\n\u001b[0;32m    849\u001b[0m         \u001b[0mn_features\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mX\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mshape\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\base.py\u001b[0m in \u001b[0;36m_validate_data\u001b[1;34m(self, X, y, reset, validate_separately, **check_params)\u001b[0m\n\u001b[0;32m    564\u001b[0m             \u001b[1;32mraise\u001b[0m \u001b[0mValueError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Validation should be done on X, y or both.\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    565\u001b[0m         \u001b[1;32melif\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mno_val_X\u001b[0m \u001b[1;32mand\u001b[0m \u001b[0mno_val_y\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 566\u001b[1;33m             \u001b[0mX\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcheck_array\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mcheck_params\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    567\u001b[0m             \u001b[0mout\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mX\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    568\u001b[0m         \u001b[1;32melif\u001b[0m \u001b[0mno_val_X\u001b[0m \u001b[1;32mand\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mno_val_y\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\utils\\validation.py\u001b[0m in \u001b[0;36mcheck_array\u001b[1;34m(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)\u001b[0m\n\u001b[0;32m    771\u001b[0m                     \u001b[1;34m\"Reshape your data either using array.reshape(-1, 1) if \"\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    772\u001b[0m                     \u001b[1;34m\"your data has a single feature or array.reshape(1, -1) \"\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 773\u001b[1;33m                     \u001b[1;34m\"if it contains a single sample.\"\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mformat\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0marray\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    774\u001b[0m                 )\n\u001b[0;32m    775\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mValueError\u001b[0m: Expected 2D array, got 1D array instead:\narray=[0. 1. 2. ... 8. 9. 8.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample."
     ]
    }
   ],
   "source": [
    "x_digits, y_digits = datasets.load_digits(return_X_y=True)\n",
    "scaler.fit_transform(x_digits)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:372: FitFailedWarning: \n",
      "25 fits failed out of a total of 25.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\nnvc00oy.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\glm_v_discrete221t0ahe\\\\glm_v_discrete-20220809161743_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discrete221t0ahe\\glm_v_discrete-20220809161743_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discrete221t0ahe\\glm_v_discrete-20220809161743_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\7qtwnk7i.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\glm_v_discretervrnkjf4\\\\glm_v_discrete-20220809161743_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discretervrnkjf4\\glm_v_discrete-20220809161743_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discretervrnkjf4\\glm_v_discrete-20220809161743_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\1ifdxhsn.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\glm_v_discreteuem621m4\\\\glm_v_discrete-20220809161743_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discreteuem621m4\\glm_v_discrete-20220809161743_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discreteuem621m4\\glm_v_discrete-20220809161743_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\a4moz80x.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\glm_v_discretex4d6ee2_\\\\glm_v_discrete-20220809161743_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discretex4d6ee2_\\glm_v_discrete-20220809161743_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discretex4d6ee2_\\glm_v_discrete-20220809161743_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\tz6zkxz6.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\glm_v_discreteraftpsep\\\\glm_v_discrete-20220809161744_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discreteraftpsep\\glm_v_discrete-20220809161744_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discreteraftpsep\\glm_v_discrete-20220809161744_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\fyafbmic.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\glm_v_discreteoy443f5m\\\\glm_v_discrete-20220809161744_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discreteoy443f5m\\glm_v_discrete-20220809161744_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discreteoy443f5m\\glm_v_discrete-20220809161744_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\wdsr4khk.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\glm_v_discretey1tblk2u\\\\glm_v_discrete-20220809161744_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discretey1tblk2u\\glm_v_discrete-20220809161744_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discretey1tblk2u\\glm_v_discrete-20220809161744_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\biwux21e.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\glm_v_discreteyrpk99_f\\\\glm_v_discrete-20220809161744_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discreteyrpk99_f\\glm_v_discrete-20220809161744_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discreteyrpk99_f\\glm_v_discrete-20220809161744_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\1b5bb75s.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\glm_v_discreteq30ei5wf\\\\glm_v_discrete-20220809161744_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discreteq30ei5wf\\glm_v_discrete-20220809161744_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discreteq30ei5wf\\glm_v_discrete-20220809161744_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\dscobg3o.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\glm_v_discrete3c8bzgv4\\\\glm_v_discrete-20220809161744_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discrete3c8bzgv4\\glm_v_discrete-20220809161744_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discrete3c8bzgv4\\glm_v_discrete-20220809161744_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\akwbbxkw.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\glm_v_discreteue_9m39a\\\\glm_v_discrete-20220809161744_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discreteue_9m39a\\glm_v_discrete-20220809161744_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discreteue_9m39a\\glm_v_discrete-20220809161744_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\vgn__sjf.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\glm_v_discretef4i29qjb\\\\glm_v_discrete-20220809161744_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discretef4i29qjb\\glm_v_discrete-20220809161744_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discretef4i29qjb\\glm_v_discrete-20220809161744_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\_30j24s8.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\glm_v_discretepql7_f4l\\\\glm_v_discrete-20220809161745_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discretepql7_f4l\\glm_v_discrete-20220809161745_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discretepql7_f4l\\glm_v_discrete-20220809161745_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\ssg_sz81.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\glm_v_discretef1im4zzy\\\\glm_v_discrete-20220809161745_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discretef1im4zzy\\glm_v_discrete-20220809161745_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discretef1im4zzy\\glm_v_discrete-20220809161745_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\ddtb9c2e.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\glm_v_discreteu9__612r\\\\glm_v_discrete-20220809161745_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discreteu9__612r\\glm_v_discrete-20220809161745_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discreteu9__612r\\glm_v_discrete-20220809161745_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\facoqhl_.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\glm_v_discretey4ov45aw\\\\glm_v_discrete-20220809161745_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discretey4ov45aw\\glm_v_discrete-20220809161745_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discretey4ov45aw\\glm_v_discrete-20220809161745_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\2cukf5fb.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\glm_v_discrete1g6w9_yn\\\\glm_v_discrete-20220809161745_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discrete1g6w9_yn\\glm_v_discrete-20220809161745_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discrete1g6w9_yn\\glm_v_discrete-20220809161745_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\e_63707p.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\glm_v_discretekh9rt30r\\\\glm_v_discrete-20220809161745_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discretekh9rt30r\\glm_v_discrete-20220809161745_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discretekh9rt30r\\glm_v_discrete-20220809161745_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\ay5kfs__.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\glm_v_discreteepxa4cfh\\\\glm_v_discrete-20220809161745_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discreteepxa4cfh\\glm_v_discrete-20220809161745_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discreteepxa4cfh\\glm_v_discrete-20220809161745_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\i8c05gya.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\glm_v_discrete738xihpx\\\\glm_v_discrete-20220809161745_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discrete738xihpx\\glm_v_discrete-20220809161745_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discrete738xihpx\\glm_v_discrete-20220809161745_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[1] is 6, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\4snf8lim.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\glm_v_discrete2un7hypj\\\\glm_v_discrete-20220809161746_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discrete2un7hypj\\glm_v_discrete-20220809161746_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discrete2un7hypj\\glm_v_discrete-20220809161746_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\0_qgcqw7.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\glm_v_discreteg4y9zhgu\\\\glm_v_discrete-20220809161746_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discreteg4y9zhgu\\glm_v_discrete-20220809161746_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discreteg4y9zhgu\\glm_v_discrete-20220809161746_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\dxj7mp4n.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\glm_v_discretepxd_1pw7\\\\glm_v_discrete-20220809161746_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discretepxd_1pw7\\glm_v_discrete-20220809161746_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discretepxd_1pw7\\glm_v_discrete-20220809161746_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\e53gra15.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmpnxixd4i6\\\\glm_v_discrete8k97j5p9\\\\glm_v_discrete-20220809161746_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discrete8k97j5p9\\glm_v_discrete-20220809161746_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmpnxixd4i6\\glm_v_discrete8k97j5p9\\glm_v_discrete-20220809161746_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\", line 394, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"c:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\", line 587, in fit\n",
      "    **self.algorithm_params if self.algorithm_params else {},\n",
      "  File \"c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\", line 1188, in sample\n",
      "    raise RuntimeError(msg)\n",
      "RuntimeError: Error during sampling:\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Exception: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\n",
      "Command and output files:\n",
      "RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n",
      " cmd (chain 1):\n",
      "\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\7frw_75w.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmp3wzglrz_\\\\glm_v_discretec2hhrqym\\\\glm_v_discrete-20220809161746_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n",
      " retcodes=[1, 1, 1, 1]\n",
      " per-chain output files (showing chain 1 only):\n",
      " csv_file:\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discretec2hhrqym\\glm_v_discrete-20220809161746_1.csv\n",
      " console_msgs (if any):\n",
      "\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmp3wzglrz_\\glm_v_discretec2hhrqym\\glm_v_discrete-20220809161746_0-stdout.txt\n",
      "Consider re-running with show_console=True if the above output is unclear!\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_search.py:972: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]\n",
      "  category=UserWarning,\n",
      "16:17:46 - cmdstanpy - INFO - CmdStan start processing\n",
      "chain 1 |\u001b[33m          \u001b[0m| 00:00 Status\n",
      "\u001b[A\n",
      "\n",
      "\u001b[A\u001b[A16:17:46 - cmdstanpy - ERROR - Chain [1] error: error during processing Operation not permitted\n",
      "16:17:46 - cmdstanpy - ERROR - Chain [3] error: error during processing Operation not permitted\n",
      "16:17:46 - cmdstanpy - ERROR - Chain [4] error: error during processing Operation not permitted\n",
      "16:17:46 - cmdstanpy - ERROR - Chain [2] error: error during processing Operation not permitted\n",
      "chain 1 |\u001b[33m██████████\u001b[0m| 00:00 Sampling completed\n",
      "chain 2 |\u001b[33m██████████\u001b[0m| 00:00 Sampling completed\n",
      "\n",
      "chain 3 |\u001b[33m██████████\u001b[0m| 00:00 Sampling completed\n",
      "\n",
      "\n",
      "chain 4 |\u001b[33m██████████\u001b[0m| 00:00 Sampling completed"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                                                                                                                                                                                                                                                                                                                                "
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "16:17:46 - cmdstanpy - INFO - CmdStan done processing.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    },
    {
     "ename": "RuntimeError",
     "evalue": "Error during sampling:\nException: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\nException: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\nException: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\nException: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\nCommand and output files:\nRunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n cmd (chain 1):\n\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmph11f5hgb\\\\j0w5_468.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmph11f5hgb\\\\glm_v_discrete0x8o61g6\\\\glm_v_discrete-20220809161746_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n retcodes=[1, 1, 1, 1]\n per-chain output files (showing chain 1 only):\n csv_file:\n\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmph11f5hgb\\glm_v_discrete0x8o61g6\\glm_v_discrete-20220809161746_1.csv\n console_msgs (if any):\n\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmph11f5hgb\\glm_v_discrete0x8o61g6\\glm_v_discrete-20220809161746_0-stdout.txt\nConsider re-running with show_console=True if the above output is unclear!",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_19448\\1877231676.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      4\u001b[0m }\n\u001b[0;32m      5\u001b[0m \u001b[0msearchgrid\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mGridSearchCV\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpipeline\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mparam_grid\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mn_jobs\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m2\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 6\u001b[1;33m \u001b[0msearchgrid\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mx_digits\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my_digits\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      7\u001b[0m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Best parameter (CV score=%0.3f):\"\u001b[0m \u001b[1;33m%\u001b[0m \u001b[0msearchgrid\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mbest_score_\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      8\u001b[0m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msearchgrid\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mbest_params_\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\model_selection\\_search.py\u001b[0m in \u001b[0;36mfit\u001b[1;34m(self, X, y, groups, **fit_params)\u001b[0m\n\u001b[0;32m    924\u001b[0m             \u001b[0mrefit_start_time\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtime\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtime\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    925\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0my\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 926\u001b[1;33m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mbest_estimator_\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mfit_params\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    927\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    928\u001b[0m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mbest_estimator_\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mfit_params\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\sklearn\\pipeline.py\u001b[0m in \u001b[0;36mfit\u001b[1;34m(self, X, y, **fit_params)\u001b[0m\n\u001b[0;32m    392\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_final_estimator\u001b[0m \u001b[1;33m!=\u001b[0m \u001b[1;34m\"passthrough\"\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    393\u001b[0m                 \u001b[0mfit_params_last_step\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mfit_params_steps\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msteps\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;33m-\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 394\u001b[1;33m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_final_estimator\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mXt\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mfit_params_last_step\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    395\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    396\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\alizm\\documents\\flatironinstitute\\scikit-stan\\scikit_stan\\generalized_linear_regression\\glm.py\u001b[0m in \u001b[0;36mfit\u001b[1;34m(self, X, y, show_console)\u001b[0m\n\u001b[0;32m    585\u001b[0m             \u001b[0mseed\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mseed_\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    586\u001b[0m             \u001b[0msig_figs\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m9\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 587\u001b[1;33m             \u001b[1;33m**\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0malgorithm_params\u001b[0m \u001b[1;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0malgorithm_params\u001b[0m \u001b[1;32melse\u001b[0m \u001b[1;33m{\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    588\u001b[0m         )\n\u001b[0;32m    589\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\alizm\\anaconda3\\envs\\intern\\lib\\site-packages\\cmdstanpy\\model.py\u001b[0m in \u001b[0;36msample\u001b[1;34m(self, data, chains, parallel_chains, threads_per_chain, seed, chain_ids, inits, iter_warmup, iter_sampling, save_warmup, thin, max_treedepth, metric, step_size, adapt_engaged, adapt_delta, adapt_init_phase, adapt_metric_window, adapt_step_size, fixed_param, output_dir, sig_figs, save_latent_dynamics, save_profile, show_progress, show_console, refresh, time_fmt, force_one_process_per_chain)\u001b[0m\n\u001b[0;32m   1186\u001b[0m                     \u001b[1;33m+\u001b[0m \u001b[1;34m' output is unclear!'\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1187\u001b[0m                 )\n\u001b[1;32m-> 1188\u001b[1;33m                 \u001b[1;32mraise\u001b[0m \u001b[0mRuntimeError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmsg\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1189\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0merrors\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1190\u001b[0m                 msg = (\n",
      "\u001b[1;31mRuntimeError\u001b[0m: Error during sampling:\nException: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\nException: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\nException: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\nException: glm_v_discrete_model_namespace::glm_v_discrete_model: y[3] is 2, but must be less than or equal to 1.000000 (in 'c:/users/alizm/documents/flatironinstitute/scikit-stan/scikit_stan/stan_files/glm_v_discrete.stan', line 11, column 4 to column 59)\nCommand and output files:\nRunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4\n cmd (chain 1):\n\t['c:\\\\users\\\\alizm\\\\documents\\\\flatironinstitute\\\\scikit-stan\\\\scikit_stan\\\\stan_files\\\\glm_v_discrete.exe', 'id=1', 'random', 'seed=1234', 'data', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmph11f5hgb\\\\j0w5_468.json', 'output', 'file=C:\\\\Users\\\\alizm\\\\AppData\\\\Local\\\\Temp\\\\tmph11f5hgb\\\\glm_v_discrete0x8o61g6\\\\glm_v_discrete-20220809161746_1.csv', 'sig_figs=9', 'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']\n retcodes=[1, 1, 1, 1]\n per-chain output files (showing chain 1 only):\n csv_file:\n\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmph11f5hgb\\glm_v_discrete0x8o61g6\\glm_v_discrete-20220809161746_1.csv\n console_msgs (if any):\n\tC:\\Users\\alizm\\AppData\\Local\\Temp\\tmph11f5hgb\\glm_v_discrete0x8o61g6\\glm_v_discrete-20220809161746_0-stdout.txt\nConsider re-running with show_console=True if the above output is unclear!"
     ]
    }
   ],
   "source": [
    "\n",
    "\n",
    "param_grid = {\n",
    "    \"pca__n_components\": [5, 15, 30, 45, 60],\n",
    "    #\"logistic__C\": np.logspace(-4, 4, 4), # this should be a specific parameter of the GLM! \n",
    "}\n",
    "searchgrid = GridSearchCV(pipeline, param_grid, n_jobs=2)\n",
    "searchgrid.fit(x_digits, y_digits)\n",
    "print(\"Best parameter (CV score=%0.3f):\" % searchgrid.best_score_)\n",
    "print(searchgrid.best_params_)\n",
    "pca.fit(x_digits)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.7.12 ('intern')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.13"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "160f8a19148fea9a7cf8ea4744d98c012bbc4693e4d32de3466f175967d43183"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
